version: '3.9'

services:
#Nginx Config
  nginx:
    image: celnet1/salesaccount-nginx:latest
    restart: always
    ports:
      - "80:80"
  
  #Backend Config
  backend:
    image: celnet1/salesaccount-be:latest
    container_name: backend
    restart: always
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USER: mysql
      DB_PASSWORD: mysql
      DB_NAME: Account_Pal
    # ports:
    #   - "8000:8000"
    depends_on:
      - mysql_db

  #frontend
  frontend:
    image: celnet1/salesaccount-fe:latest
    container_name: client
    # networks:
    #   - appnet
    # # restart: always
    # ports: check default.conf in the nginx folder
    #   - "3000:3000"

  # database  
  # db:
  #   image: postgres:latest
  #   container_name: postgres-db
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - 5432:5432
  #   volumes: 
  #     - db:/var/lib/postgresql/data

  mysql_db:
    image: mysql:latest
    container_name: sql-db
    environment:
      - MYSQL_DATABASE=Account_Pal
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

# used to have a UI for the database  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql_db
    ports:
      - 8081:8080
    # networks:
    #   - appnet

# link all docker containers to the same image
# networks:
#   appnet:
#     driver: bridge
# bind volumes
volumes:
  db:
    driver: local
