const blogList = [
	{
		id: 1,
		slug: 'Common-Accounting-Terms-Explained',
		title: 'Common-Accounting-Terms-Explained',
		category: 'Accounting',
		higlight:
			'Do you feel lost when accounting jargons are used during sales conversations? Then, this is for you.',
		author: 'Olivia Rhye',
		dateCreated: '20 Jan 2022',
		avatarImage: '../assets/avatar-full.svg',
		thumbnail: '../assets/pexels1.svg',
	},
	{
		id: 2,
		slug: '3 Effective Debt Management Practices',
		title: '3 Effective Debt Management Practices',
		category: 'Finance',
		higlight: 'Debt can be beneficial to your company when managed properly.',
		author: 'Olivia Rhye',
		dateCreated: '20 Jan 2022',
		avatarImage: '../assets/avatar-full.svg',
		thumbnail: '../assets/pexels2.svg',
	},
	{
		id: 3,
		slug: 'Business Accounting 101',
		title: 'Business Accounting 101',
		category: 'Accounting',
		higlight:
			'All the basics you need to know about accounting as a business owner.',
		author: 'Olivia Rhye',
		dateCreated: '20 Jan 2022',
		avatarImage: '../assets/avatar-full.svg',
		thumbnail: '../assets/pexels3.svg',
	},
	{
		id: 4,
		slug: '5 Steps to Preventing Expense Fraud',
		title: '5 Steps to Preventing Expense Fraud',
		category: 'Fraud',
		higlight: 'Actionable Steps to prevent fraud among  employees.',
		author: 'Olivia Rhye',
		dateCreated: '20 Jan 2022',
		avatarImage: '../assets/avatar-full.svg',
		thumbnail: '../assets/pexels4.svg',
	},
	{
		id: 5,
		slug: 'How to Overcome Impulsive Spending',
		title: 'How to Overcome Impulsive Spending',
		category: 'Lifestyle',
		higlight: 'Learn how to overcome random expenses and impulsive spendings.',
		author: 'Olivia Rhye',
		dateCreated: '20 Jan 2022',
		avatarImage: '../assets/avatar-full.svg',
		thumbnail: '../assets/pexels5.svg',
	},
	{
		id: 6,
		slug: 'A Business Owners Accounting Checklist',
		title: 'A Business Owners Accounting Checklist',
		category: 'Accounting',
		higlight:
			'A detailed accounting checklist for small and medium scale businesses',
		author: 'Olivia Rhye',
		dateCreated: '20 Jan 2022',
		avatarImage: '../assets/avatar-full.svg',
		thumbnail: '../assets/pexels6.svg',
	},
	{
		id: 7,
		slug: 'Steps to Avoid Business Bankruptcy',
		title: '3 Effective Debt Management Practices',
		category: 'Business',
		higlight:
			'What steps can be taken to ensure that a business doesn’t end up having to file for bankruptcy? Find out in this article.',
		author: 'Olivia Rhye',
		dateCreated: '20 Jan 2022',
		avatarImage: '../assets/avatar-full.svg',
		thumbnail: '../assets/pexels7.svg',
	},
	{
		id: 8,
		slug: 'The Ultimate Guide to Use Our Website',
		title: 'The Ultimate Guide to Use Our Website',
		category: 'Product',
		higlight: 'A step-by-step guide on our to navigate our website.',
		author: 'Olivia Rhye',
		dateCreated: '20 Jan 2022',
		avatarImage: '../assets/avatar-full.svg',
		thumbnail: '../assets/pexels8.svg',
	},
	{
		id: 9,
		slug: 'Accounting Trends to Look Forward to in 2023',
		title: 'Accounting Trends to Look Forward to in 2023',
		category: 'Accounting',
		higlight: 'Watch out for these accounting threads in 2023.',
		author: 'Olivia Rhye',
		dateCreated: '20 Jan 2022',
		avatarImage: '../assets/avatar-full.svg',
		thumbnail: '../assets/pexels9.svg',
	},
];

export default blogList;
